graph LR
    A[CloudFormation template] -->|Deploys| B[Web App]
    B -->|Vulnerable to| C[SQL Injection Execution]
    C -->|Leads to| D[Arbitrary Code Execution]
    D -->|Results in| E[Steal data]
    E -->|Detected by| F[GuardDuty]
