graph TD
    A[KMS] -->|Provides Key| B[KMS Encryption Key]
    B -->|Encrypts| C[DynamoDB]
    D[IAM Admin User] -->|Access ✅| B
    E[Test User] -->|Access ❌| B

    subgraph AWS Services
        A
        C
    end

    subgraph IAM
        D
        E
    end


    A[KMS] -->|Provides Key| B[KMS Encryption Key]
    B -->|Encrypts| C[DynamoDB]
    D[IAM Admin User] -->|Access ✅| B
    E[Test User] -->|Access ✅| B

    subgraph AWS Services
        A
        C
    end

    subgraph IAM
        D
        E
    end 



